// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/patterns/button/Button.vue')['default']
    ColorSelection: typeof import('./components/editor/toolbar/ColorSelection.vue')['default']
    Editor: typeof import('./components/editor/Editor.vue')['default']
    Footer: typeof import('./components/patterns/layout/Footer.vue')['default']
    Header: typeof import('./components/patterns/layout/Header.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toolbar: typeof import('./components/editor/toolbar/Toolbar.vue')['default']
    ToolbarActions: typeof import('./components/editor/toolbar/ToolbarActions.vue')['default']
    ToolbarButton: typeof import('./components/editor/toolbar/ToolbarButton.vue')['default']
  }
}
